In [14]:
import pandas as pd

In [19]:
import pandas as pd

df1 = pd.read_csv("olist_products_dataset.csv")

df2 = pd.read_csv("olist_order_payments_dataset.csv")

df3 = pd.read_csv("imdb_top_1000.csv")

df4 = pd.read_excel("olist_customers_dataset.xlsx")



# Check karne ke liye
print(df1.shape, df2.shape, df3.shape, df4.shape)

(32951, 9) (103886, 5) (1000, 16)

In [20]:
print (df1.size , df2.size, df3.size , df4.size)

296559 519430 16000

In [45]:
print(df1.columns)
print("\n-------------------------\n") 

print("payment_Table ",df2.columns)
print("\n-------------------------\n") 

print("top_1000",df3.columns)
print("\n --------------------------------\n")

print("customer", df4.columns)

Index(['product_id', 'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='object')

-------------------------

payment_Table  Index(['order_id', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value'],
      dtype='object')

-------------------------

top_1000 Index(['Poster_Link', 'Series_Title', 'Released_Year', 'Certificate',
       'Runtime', 'Genre', 'IMDB_Rating', 'Overview', 'Meta_score', 'Director',
       'Star1', 'Star2', 'Star3', 'Star4', 'No_of_Votes', 'Gross'],
      dtype='object')

 --------------------------------

customer Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state', 'State', 'geolocation_lat',
       'geolocation_lng', 'Region', 'Population'],
      dtype='object')

In [46]:
print(df1.isnull().sum())
print("\n-------------------------\n")   # separator

print(df2.isnull().sum())
print("\n-------------------------\n")   # separator

print(df3.isnull().sum())
print("\n-------------------------\n")

print(df.isnull().sum())

product_id                      0
product_category_name         623
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

-------------------------

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

-------------------------

Poster_Link        0
Series_Title       0
Released_Year      0
Certificate      101
Runtime            0
Genre              0
IMDB_Rating        0
Overview           0
Meta_score       157
Director           0
Star1              0
Star2              0
Star3              0
Star4              0
No_of_Votes        0
Gross            169
dtype: int64

-------------------------

product_id                      0
product_category_name         623
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [47]:
print(df1.duplicated().sum())
print("\n-------------------------\n") 

print(df2.duplicated().sum())
print("\n-------------------------\n") 

print(df3.duplicated().sum())
print("\n-------------------------\n")


print(df4.duplicated().sum())

0

-------------------------

0

-------------------------

0

-------------------------

0

In [48]:
df4.head(5)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,State,geolocation_lat,geolocation_lng,Region,Population
0,05b005e82f3f2dcc41b5504f00484e50,3ef8c1513fc80fb905ccd8d57da5e9b8,1037,sao paulo,SP,São Paulo,-23.545621,-46.639292,Southeast,41164000
1,9a02295e3381803554347ab4dc1ab41b,182491a144858edd68163675689069d6,1046,sao paulo,SP,São Paulo,-23.546081,-46.644820,Southeast,41164000
2,51795c9dc161dc05ef36dc8460dfa7e7,86ef1d99643569be4c21378742544d2e,1046,sao paulo,SP,São Paulo,-23.546081,-46.644820,Southeast,41164000
3,d9e67dbdc0e7ff5a0ccbb30c9414fbd2,dbee72d5fc5c73b8d3537534c9ff3fdf,1046,sao paulo,SP,São Paulo,-23.546081,-46.644820,Southeast,41164000
4,e41ca8cd2c3ae3aec718fa68a2ff49d4,6f8e7d40046694539c87b98cb5096a28,1046,sao paulo,SP,São Paulo,-23.546081,-46.644820,Southeast,41164000

In [44]:

df4

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,State,geolocation_lat,geolocation_lng,Region,Population
0,05b005e82f3f2dcc41b5504f00484e50,3ef8c1513fc80fb905ccd8d57da5e9b8,1037,sao paulo,SP,São Paulo,-23.545621,-46.639292,Southeast,41164000
1,9a02295e3381803554347ab4dc1ab41b,182491a144858edd68163675689069d6,1046,sao paulo,SP,São Paulo,-23.546081,-46.644820,Southeast,41164000
2,51795c9dc161dc05ef36dc8460dfa7e7,86ef1d99643569be4c21378742544d2e,1046,sao paulo,SP,São Paulo,-23.546081,-46.644820,Southeast,41164000
3,d9e67dbdc0e7ff5a0ccbb30c9414fbd2,dbee72d5fc5c73b8d3537534c9ff3fdf,1046,sao paulo,SP,São Paulo,-23.546081,-46.644820,Southeast,41164000
4,e41ca8cd2c3ae3aec718fa68a2ff49d4,6f8e7d40046694539c87b98cb5096a28,1046,sao paulo,SP,São Paulo,-23.546081,-46.644820,Southeast,41164000
...,...,...,...,...,...,...,...,...,...,...
99436,80cf55a439bbb373aea40a08515fb39b,22770768e9c650851b78132a4d881128,22790,rio de janeiro,RJ,Rio de Janeiro,-23.011335,-43.450256,Southeast,15593000
99437,f3309994e8de398daa7ebcd5479cf689,ce4ea52bbd9acb2f47afbc1486b0fa91,22790,rio de janeiro,RJ,Rio de Janeiro,-23.011335,-43.450256,Southeast,15593000
99438,a408804c2ca25f708718ea11750de00f,dbab7e7f2f9001c2afd509d4116ca726,22790,rio de janeiro,RJ,Rio de Janeiro,-23.011335,-43.450256,Southeast,15593000
99439,fd636f2e6a579b3241357a76b71b88e6,43edb847a2edc6849200624355f20159,22790,rio de janeiro,RJ,Rio de Janeiro,-23.011335,-43.450256,Southeast,15593000
99440,f9c989b75558c119a7ce8e9f3c2b8f45,ce13190d9ef1e855dc50ecea9a1ef809,22790,rio de janeiro,RJ,Rio de Janeiro,-23.011335,-43.450256,Southeast,15593000

In [63]:
df4['customer_state'].value_counts()

customer_state
SP    41746
RJ    12852
MG    11635
RS     5466
PR     5045
SC     3637
BA     3380
DF     2140
ES     2033
GO     2020
PE     1652
CE     1336
PA      975
MT      907
MA      747
MS      715
PB      536
PI      495
RN      485
AL      413
SE      350
TO      280
RO      253
AM      148
AC       81
AP       68
RR       46
Name: count, dtype: int64

In [62]:
df4['customer_state'].value_counts().head(5)

customer_state
SP    41746
RJ    12852
MG    11635
RS     5466
PR     5045
Name: count, dtype: int64

In [61]:
df4['customer_state'].unique().sum()

'SPPIGOMGMTESMARJCEPRBAROPARSPBALSEPETORNAPAMRRACMSDFSC'

In [60]:
df4.columns

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state', 'State', 'geolocation_lat',
       'geolocation_lng', 'Region', 'Population'],
      dtype='object')